In [1]:
import numpy as np

In [3]:
!pip install numpy


In [4]:
arr=np.array([1,2,3])

In [5]:
arr

array([1, 2, 3])

In [6]:
arr2=np.array([[1,4,3],[2,6,4]])

In [7]:
arr2


array([[1, 4, 3],
       [2, 6, 4]])

In [8]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [12]:
np.full((2,6),7)

array([[7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7]])

In [13]:
np.eye(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [15]:
np.arange(9,100,9)

array([ 9, 18, 27, 36, 45, 54, 63, 72, 81, 90, 99])

In [17]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [18]:
myarr=np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13]])

In [19]:
myarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [20]:
myarr.shape

(4, 3)

In [21]:
myarr.size

12

In [22]:
myarr.ndim

2

In [23]:
myarr.dtype

dtype('int64')

In [24]:
myarr=np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13]],dtype='float32')

In [25]:
myarr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [11., 12., 13.]], dtype=float32)

In [26]:
myarr=np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13]])
myarr.shape

(4, 3)

In [28]:
reshaped=myarr.reshape((2,6))
reshaped

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 11, 12, 13]])

In [30]:
myarr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])