In [1]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13]])

In [2]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [3]:
flat=arr.flatten()

In [4]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [7]:
flat[0]

np.int64(1)

In [8]:
flat[3]

np.int64(4)

In [9]:
flat[3:6]

array([4, 5, 6])

In [10]:
flat[:6]

array([1, 2, 3, 4, 5, 6])

In [11]:
flat[3:]

array([ 4,  5,  6,  7,  8,  9, 11, 12, 13])

In [13]:
print(arr[::2])

[[1 2 3]
 [7 8 9]]


In [14]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [15]:
b=flat[3:7]
b

array([4, 5, 6, 7])

In [16]:
b[0]= 4444

In [17]:
b

array([4444,    5,    6,    7])

In [18]:
flat

array([   1,    2,    3, 4444,    5,    6,    7,    8,    9,   11,   12,
         13])

In [20]:
arr=np.array([2,4,67,8,3,65,876,87,9,76])

In [21]:
arr[[1,4,5]]

array([ 4,  3, 65])

In [22]:
arr[arr>34]

array([ 67,  65, 876,  87,  76])