In [1]:
import numpy as np


In [4]:
arr = np.array ([3,5,2,33,2,1,10,1])

In [5]:
np.mean(arr)

np.float64(7.125)

In [8]:
np.min(arr)

np.int64(1)

In [9]:
np.max(arr)

np.int64(33)

In [10]:
np.std(arr)

np.float64(10.16658128379447)

In [11]:
np.var(arr)

np.float64(103.359375)

In [12]:
np.sum(arr)

np.int64(57)

In [13]:
np.prod(arr)

np.int64(19800)

In [14]:
np.median(arr)

np.float64(2.5)

In [15]:
np.percentile(arr, 50)  # For the 50th percentile (median)

np.float64(2.5)

In [16]:
np.argmin(arr)

np.int64(5)

In [17]:
np.argmax(arr)

np.int64(3)

In [19]:
np.unique(arr)

array([ 1,  2,  3,  5, 10, 33])

In [20]:
np.diff(arr)

array([  2,  -3,  31, -31,  -1,   9,  -9])

In [21]:
np.cumsum(arr)

array([ 3,  8, 10, 43, 45, 46, 56, 57])