In [1]:
import numpy as np
arr = np.array ([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

In [2]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
arr[0]

array([1, 2, 3])

In [5]:
np.sum(arr, axis=1)

array([ 6, 15, 24])

In [6]:
arr[0][1]

np.int64(2)

In [7]:
arr[0,1]

np.int64(2)

In [9]:
arr[2,2]

np.int64(9)

In [11]:
arr3D = np.array([[[1, 2, 3], [4, 5, 6]],
[[7, 8, 9], [10, 11, 12]]])

In [12]:
arr3D

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [13]:
arr3D[0,1,2]

np.int64(6)

In [14]:
arr3D[:,0,:]

array([[1, 2, 3],
       [7, 8, 9]])